platform :ios, '9.0'

target 'iPhoneModel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iPhoneModel

  target 'iPhoneModelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iPhoneModelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Masonry'
pod 'AFNetworking'

end
